apiVersion: v1
kind: Namespace
metadata:
  name: k8-ldap-configmap
  labels:
    app.kubernetes.io/name: k8-ldap-configmap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8-ldap-configmap
  namespace: k8-ldap-configmap
  labels:
    app.kubernetes.io/name: k8-ldap-configmap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8-ldap-configmap
  namespace: k8-ldap-configmap
  labels:
    app.kubernetes.io/name: k8-ldap-configmap
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8-ldap-configmap
  namespace: k8-ldap-configmap
  labels:
    app.kubernetes.io/name: k8-ldap-configmap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8-ldap-configmap
subjects:
- kind: ServiceAccount
  name: k8-ldap-configmap
  namespace: k8-ldap-configmap
