{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8-ldap-configmap.fullname" . }}
  namespace: {{ include "k8-ldap-configmap.namespace" . }}
  labels:
    {{- include "k8-ldap-configmap.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
  resourceNames:
{{- range .Values.mappers }}
  - {{ printf "%s-map" . }}
{{- end }}
{{- end }}
