apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8-ldap-configmap.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "k8-ldap-configmap.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
