apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8-ldap-configmap.fullname" . }}
  namespace: {{ .Values.namespaceConfigMap | default .Release.Namespace | quote }}
  labels:
    {{- include "k8-ldap-configmap.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8-ldap-configmap.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8-ldap-configmap.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
