{{- if or .Values.ldapBindPassword .Values.ldapTLSCACert }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "k8-ldap-configmap.fullname" . }}
  namespace: {{ include "k8-ldap-configmap.namespace" . }}
  labels:
    {{- include "k8-ldap-configmap.labels" . | nindent 4 }}
data:
{{- if .Values.ldapBindPassword }}
  ldap-bind-password: |-
    {{ .Values.ldapBindPassword | b64enc }}
{{- end }}
{{- if .Values.ldapTLSCACert }}
  ldap-tls-ca-cert: |-
    {{ .Values.ldapTLSCACert | b64enc }}
{{- end }}
{{- end }}
