{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8-ldap-configmap.fullname" . }}
  namespace: {{ include "k8-ldap-configmap.namespace" . }}
  labels:
    {{- include "k8-ldap-configmap.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: '{{ .Values.service.port }}'
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8-ldap-configmap.selectorLabels" . | nindent 4 }}
{{- end -}}
