{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8-ldap-configmap.serviceAccountName" . }}
  namespace: {{ include "k8-ldap-configmap.namespace" . }}
  labels:
    {{- include "k8-ldap-configmap.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
