apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8-ldap-configmap.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "k8-ldap-configmap.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
