name: Release Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-docker:
    runs-on: ubuntu-latest
    name: Release Docker
    steps:
      - name: Set version
        id: version
        run: |
          ref=${GITHUB_REF#refs/*/}
          if [ $ref = "main" ]; then
            version="latest"
          else
            version=$ref
          fi
          echo ::set-output name=ref::$ref
          echo ::set-output name=version::$version
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: oscrobot
          password: ${{ secrets.OSC_ROBOT_DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ohiosupercomputer/k8-ldap-configmap:${{ steps.version.outputs.version }}
          build-args: |
            VERSION=${{ steps.version.outputs.ref }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
