name: Release Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-docker:
    runs-on: ubuntu-latest
    name: Release Docker
    steps:
      - name: Set version
        run: |
          ref=${GITHUB_REF#refs/*/}
          if [ $ref = "main" ]; then
            version="latest"
          else
            version=$ref
          fi
          echo "REF=${ref}" >> $GITHUB_ENV
          echo "VERSION=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v12
        with:
          username: oscrobot
          password: ${{ secrets.OSC_ROBOT_DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ohiosupercomputer/k8-ldap-configmap:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.REF }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
