name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --timeout=2m
      - name: Run tests
        run: make all
      - name: Run coverage
        run: make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make build
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --snapshot
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: k8-ldap-configmap:latest
          outputs: type=docker,dest=/tmp/k8-ldap-configmap.tar
      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/k8-ldap-configmap.tar
  test-helm:
    needs: [build]
    runs-on: ubuntu-latest
    name: Test Helm Chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp
      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/cf.yaml --check-version-increment=false
      - name: Create kind cluster
        uses: container-tools/kind-action@v1
      - name: Load image
        run: |
          docker load --input /tmp/k8-ldap-configmap.tar
          docker tag k8-ldap-configmap:latest kind-registry:5000/k8-ldap-configmap:latest
          docker push kind-registry:5000/k8-ldap-configmap:latest
      - name: Update chart values
        run: |
          sed -i \
            -e 's|tag:.*|tag: latest|g' \
            -e 's|repository:.*|repository: kind-registry:5000/k8-ldap-configmap|g' \
            -e 's|ldapUrl:.*|ldapUrl: ldap://openldap:389|g' \
            -e 's|ldapGroupBaseDN:.*|ldapGroupBaseDN: dc=test|g' \
            -e 's|ldapUserBaseDN:.*|ldapUserBaseDN: dc=test|g' \
            charts/k8-ldap-configmap/values.yaml
          cat charts/k8-ldap-configmap/values.yaml
      - name: Run chart-testing (install)
        run: ct install --config .github/config/cf.yaml
